/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SampleManagerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var { exec } = require("child_process");
var DEFAULT_SETTINGS = {
  pythonPath: "/Users/yang-uijin/Library/CloudStorage/Dropbox/Sample_Manager/.venv/bin/python",
  scriptPath: "/Users/yang-uijin/Library/CloudStorage/Dropbox/Sample_Manager/lab_main.py"
};
var SampleManagerPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    const ribbonIconEl = this.addRibbonIcon("flask-conical", "Launch Sample Manager", (evt) => {
      this.launchSampleManager();
    });
    ribbonIconEl.addClass("sample-manager-plugin-ribbon-class");
    this.addCommand({
      id: "launch-sample-manager",
      name: "Launch Sample Manager",
      callback: () => {
        this.launchSampleManager();
      }
    });
    this.addSettingTab(new SampleManagerSettingTab(this.app, this));
    this.registerObsidianProtocolHandler("sample-manager", (params) => {
      if (params.sample && params.step) {
        this.launchSampleManagerWithNav(params.sample, params.step);
      } else {
        this.launchSampleManager();
      }
    });
  }
  launchSampleManager() {
    new import_obsidian.Notice("Launching Sample Manager...");
    const command = `"${this.settings.pythonPath}" "${this.settings.scriptPath}"`;
    exec(command, (error, stdout, stderr) => {
      if (error) {
        console.error(`Error launching Sample Manager: ${error.message}`);
        new import_obsidian.Notice(`Error launching Sample Manager. Check console for details.`);
        return;
      }
      if (stderr) {
        const filteredStderr = stderr.split("\n").filter((line) => {
          return !line.includes("TSM AdjustCapsLockLEDForKeyTransitionHandling") && !line.includes("IMKCFRunLoopWakeUpReliable");
        }).join("\n").trim();
        if (filteredStderr) {
          console.error(`Sample Manager stderr: ${filteredStderr}`);
        }
      }
      console.log(`Sample Manager stdout: ${stdout}`);
    });
  }
  launchSampleManagerWithNav(sampleId, stepId) {
    new import_obsidian.Notice("Launching Sample Manager (navigating to step)...");
    const command = `"${this.settings.pythonPath}" "${this.settings.scriptPath}" --navigate "${sampleId}" "${stepId}"`;
    exec(command, (error, stdout, stderr) => {
      if (error) {
        console.error(`Error launching Sample Manager: ${error.message}`);
        new import_obsidian.Notice(`Error launching Sample Manager. Check console for details.`);
        return;
      }
      if (stderr) {
        const filteredStderr = stderr.split("\n").filter((line) => {
          return !line.includes("TSM AdjustCapsLockLEDForKeyTransitionHandling") && !line.includes("IMKCFRunLoopWakeUpReliable");
        }).join("\n").trim();
        if (filteredStderr) {
          console.error(`Sample Manager stderr: ${filteredStderr}`);
        }
      }
      console.log(`Sample Manager stdout: ${stdout}`);
    });
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var SampleManagerSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Python Executable Path").setDesc("Absolute path to the Python environment containing the dependencies.").addText((text) => text.setPlaceholder("Enter absolute path").setValue(this.plugin.settings.pythonPath).onChange(async (value) => {
      this.plugin.settings.pythonPath = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Script Path").setDesc("Absolute path to lab_main.py").addText((text) => text.setPlaceholder("Enter absolute path").setValue(this.plugin.settings.scriptPath).onChange(async (value) => {
      this.plugin.settings.scriptPath = value;
      await this.plugin.saveSettings();
    }));
  }
};
