/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SampleManagerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var { exec, spawn } = require("child_process");
var DEFAULT_SETTINGS = {
  pythonPath: "/Users/yang-uijin/Library/CloudStorage/Dropbox/Sample_Manager/.venv/bin/python",
  scriptPath: "/Users/yang-uijin/Library/CloudStorage/Dropbox/Sample_Manager/lab_main.py"
};
var SampleManagerPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    // Ribbon icon is provided by the laminar plugin; this plugin only
    // registers the command, settings tab, and protocol handler.
    this.addCommand({
      id: "launch-sample-manager",
      name: "Launch Sample Manager",
      callback: () => {
        this.launchSampleManager();
      }
    });
    this.addSettingTab(new SampleManagerSettingTab(this.app, this));
    this.registerObsidianProtocolHandler("sample-manager", (params) => {
      if (params.sample && params.step) {
        this.launchSampleManagerWithNav(params.sample, params.step);
      } else {
        this.launchSampleManager();
      }
    });
  }
  _spawnDetached(args) {
    // spawn + detached + stdio:'ignore' + unref fully detaches the child from
    // Obsidian's event loop. This prevents the Tk GUI process from inheriting
    // the parent's focus/activation context, which on macOS otherwise keeps
    // the window hidden behind Obsidian.
    const fs = require("fs");
    const path = require("path");
    const pythonPath = this.settings.pythonPath;
    const scriptPath = this.settings.scriptPath;
    console.log("[SampleManager] launching", { pythonPath, scriptPath, args });
    if (!fs.existsSync(pythonPath)) {
      const msg = `Python not found: ${pythonPath}`;
      console.error("[SampleManager]", msg);
      new import_obsidian.Notice(msg);
      return;
    }
    if (!fs.existsSync(scriptPath)) {
      const msg = `Script not found: ${scriptPath}`;
      console.error("[SampleManager]", msg);
      new import_obsidian.Notice(msg);
      return;
    }
    try {
      const child = spawn(pythonPath, args, {
        detached: true,
        stdio: "ignore",
        cwd: path.dirname(scriptPath),
      });
      child.on("error", (err) => {
        console.error("[SampleManager] spawn error:", err);
        new import_obsidian.Notice(`Sample Manager spawn error: ${err.message}`);
      });
      child.on("spawn", () => {
        console.log("[SampleManager] spawned pid=", child.pid);
      });
      child.unref();
    } catch (e) {
      console.error("[SampleManager] launch exception:", e);
      new import_obsidian.Notice(`Sample Manager launch exception: ${e.message}`);
    }
  }
  launchSampleManager() {
    new import_obsidian.Notice("Launching Sample Manager...");
    this._spawnDetached([this.settings.scriptPath]);
  }
  launchSampleManagerWithNav(sampleId, stepId) {
    new import_obsidian.Notice("Launching Sample Manager (navigating to step)...");
    this._spawnDetached([this.settings.scriptPath, "--navigate", sampleId, stepId]);
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var SampleManagerSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Python Executable Path").setDesc("Absolute path to the Python environment containing the dependencies.").addText((text) => text.setPlaceholder("Enter absolute path").setValue(this.plugin.settings.pythonPath).onChange(async (value) => {
      this.plugin.settings.pythonPath = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Script Path").setDesc("Absolute path to lab_main.py").addText((text) => text.setPlaceholder("Enter absolute path").setValue(this.plugin.settings.scriptPath).onChange(async (value) => {
      this.plugin.settings.scriptPath = value;
      await this.plugin.saveSettings();
    }));
  }
};
